# Generated by Django 3.1.3 on 2020-11-14 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misionapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'asignacion',
                'managed': False,
            },
        ),
    ]
